<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\RecipeIngredient;
use Illuminate\Support\Facades\DB;

class RecipeIngredientsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('recipe_ingredients')->insert([
            // 1
            [
                'user_id' => 1,
                'recipe_id' => 1,
                'recipe_ingredient_name' => "スパゲティ", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "麺類",
                'recipe_ingredient_quantity' => "200g",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 1,
                'recipe_ingredient_name' => "ベーコン", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "肉類",
                'recipe_ingredient_quantity' => "4枚",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 1,
                'recipe_ingredient_name' => "モッツァレラチーズ", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "1袋(100g)",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 1,
                'recipe_ingredient_name' => "なす", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "野菜料理",
                'recipe_ingredient_quantity' => "2本",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 1,
                'recipe_ingredient_name' => "にんにく", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "1かけ",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 1,
                'recipe_ingredient_name' => "オリーブオイル", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "大さじ2",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 1,
                'recipe_ingredient_name' => "トマト缶", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "1/2缶(200g)",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 1,
                'recipe_ingredient_name' => "塩", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "小さじ1/2",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 1,
                'recipe_ingredient_name' => "こしょう", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "少々",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 1,
                'recipe_ingredient_name' => "コンソメ", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "小さじ1/2",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 1,
                'recipe_ingredient_name' => "バジル", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "4枚",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 2
            [
                'user_id' => 1,
                'recipe_id' => 2,
                'recipe_ingredient_name' => "ごはん", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "ご飯もの",
                'recipe_ingredient_quantity' => "どんぶり2杯(400g)",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 2,
                'recipe_ingredient_name' => "牛切り落とし肉", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "肉類",
                'recipe_ingredient_quantity' => "200g",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 2,
                'recipe_ingredient_name' => "塩こしょう", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "少々",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 2,
                'recipe_ingredient_name' => "にんにく", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "2かけ",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 2,
                'recipe_ingredient_name' => "オリーブオイル", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "大さじ1",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 2,
                'recipe_ingredient_name' => "白いりごま", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "大さじ2",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 2,
                'recipe_ingredient_name' => "細ねぎ(刻み)", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "野菜類",
                'recipe_ingredient_quantity' => "適量",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 2,
                'recipe_ingredient_name' => "しょうゆ", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "大さじ1/2",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 2,
                'recipe_ingredient_name' => "塩", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "小さじ1/3",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 2,
                'recipe_ingredient_name' => "有塩バター", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "15g",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 3
            [
                'user_id' => 1,
                'recipe_id' => 3,
                'recipe_ingredient_name' => "スパゲティ", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "ご飯もの",
                'recipe_ingredient_quantity' => "160g",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 3,
                'recipe_ingredient_name' => "ベーコン", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "肉類",
                'recipe_ingredient_quantity' => "4枚",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 3,
                'recipe_ingredient_name' => "レタス", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "4枚(120g)",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 3,
                'recipe_ingredient_name' => "にんにく", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "1かけ",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 3,
                'recipe_ingredient_name' => "唐辛子", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "少々",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 3,
                'recipe_ingredient_name' => "オリーブオイル", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "大さじ2",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 3,
                'recipe_ingredient_name' => "スパゲティのゆで汁", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "野菜類",
                'recipe_ingredient_quantity' => "大さじ2",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 3,
                'recipe_ingredient_name' => "塩", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "小さじ1/2",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 3,
                'recipe_ingredient_name' => "こしょう", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "少々",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 4
            [
                'user_id' => 1,
                'recipe_id' => 4,
                'recipe_ingredient_name' => "ごはん", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "ご飯もの",
                'recipe_ingredient_quantity' => "どんぶり2杯(400g)",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 4,
                'recipe_ingredient_name' => "豚ひき肉", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "肉類",
                'recipe_ingredient_quantity' => "150g",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 4,
                'recipe_ingredient_name' => "玉ねぎ", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "1/2個",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 4,
                'recipe_ingredient_name' => "しいたけ", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "2個",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 4,
                'recipe_ingredient_name' => "半熟ゆで卵", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "1個",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 4,
                'recipe_ingredient_name' => "カットトマト缶", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "1/2缶(200g)",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 4,
                'recipe_ingredient_name' => "酒", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "野菜類",
                'recipe_ingredient_quantity' => "大さじ2",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 4,
                'recipe_ingredient_name' => "しょうゆ", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "大さじ1",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 4,
                'recipe_ingredient_name' => "みそ", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "大さじ1/2",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 4,
                'recipe_ingredient_name' => "おろしにんにく", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "小さじ1/2",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 5
            [
                'user_id' => 1,
                'recipe_id' => 5,
                'recipe_ingredient_name' => "スパゲティ", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "ご飯もの",
                'recipe_ingredient_quantity' => "200g",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 5,
                'recipe_ingredient_name' => "菜の花", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "肉類",
                'recipe_ingredient_quantity' => "1束",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 5,
                'recipe_ingredient_name' => "トマト", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "1/2個",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 5,
                'recipe_ingredient_name' => "にんにく", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "1かけ",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 5,
                'recipe_ingredient_name' => "赤唐辛子", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "1本",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 5,
                'recipe_ingredient_name' => "昆布茶", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "少々",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 5,
                'recipe_ingredient_name' => "オリーブオイル", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "野菜類",
                'recipe_ingredient_quantity' => "大さじ2",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 5,
                'recipe_ingredient_name' => "しょうゆ", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "大さじ1",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 5,
                'recipe_ingredient_name' => "塩", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "少々",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 5,
                'recipe_ingredient_name' => "こしょう", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "少々",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 6
            [
                'user_id' => 1,
                'recipe_id' => 6,
                'recipe_ingredient_name' => "スパゲティ", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "ご飯もの",
                'recipe_ingredient_quantity' => "80g",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 6,
                'recipe_ingredient_name' => "シーフードミックス[冷凍]", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "肉類",
                'recipe_ingredient_quantity' => "100g",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 6,
                'recipe_ingredient_name' => "おろしにんにく", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "少々",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 6,
                'recipe_ingredient_name' => "オリーブオイル", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "小さじ1",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 6,
                'recipe_ingredient_name' => "有塩バター", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "10g",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 6,
                'recipe_ingredient_name' => "大葉", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "2枚",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 6,
                'recipe_ingredient_name' => "酒", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "野菜類",
                'recipe_ingredient_quantity' => "大さじ1",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 6,
                'recipe_ingredient_name' => "塩", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "小さじ1/3",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 6,
                'recipe_ingredient_name' => "めんつゆ", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "大さじ1/2",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 6,
                'recipe_ingredient_name' => "水", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "250cc",
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 7
            [
                'user_id' => 1,
                'recipe_id' => 7,
                'recipe_ingredient_name' => "じゃがいも", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "ご飯もの",
                'recipe_ingredient_quantity' => "2個",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 7,
                'recipe_ingredient_name' => "豚ロース肉", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "肉類",
                'recipe_ingredient_quantity' => "2枚",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 7,
                'recipe_ingredient_name' => "スナップえんどう", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "6個",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 7,
                'recipe_ingredient_name' => "にんにく", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "1かけ",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 7,
                'recipe_ingredient_name' => "塩", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "少々",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 7,
                'recipe_ingredient_name' => "バター", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "少々",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 7,
                'recipe_ingredient_name' => "しょうゆ", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "野菜類",
                'recipe_ingredient_quantity' => "少々",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 7,
                'recipe_ingredient_name' => "みりん", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "少々",
                'created_at' => now(),
                'updated_at' => now(),
            ],
             // 8
             [
                'user_id' => 1,
                'recipe_id' => 8,
                'recipe_ingredient_name' => "じゃがいも", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "ご飯もの",
                'recipe_ingredient_quantity' => "2個",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 8,
                'recipe_ingredient_name' => "玉ねぎ", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "肉類",
                'recipe_ingredient_quantity' => "1/4個",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 8,
                'recipe_ingredient_name' => "きゅうり", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "1/4本",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 8,
                'recipe_ingredient_name' => "にんじん", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "1/4本",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 8,
                'recipe_ingredient_name' => "ハム", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "2枚",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 8,
                'recipe_ingredient_name' => "マヨネーズ", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "大さじ5",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 8,
                'recipe_ingredient_name' => "塩", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "野菜類",
                'recipe_ingredient_quantity' => "少々",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 8,
                'recipe_ingredient_name' => "こしょう", 
                'recipe_ingredient_image_path' => "https://recipe-img-bucket.s3-ap-northeast-1.amazonaws.com/recipes/no_image.png", 
                'recipe_ingredient_category' => "そのほか",
                'recipe_ingredient_quantity' => "少々",
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}
