<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\RecipeIngredient;
use Illuminate\Support\Facades\DB;

class RecipeIngredientsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('recipe_ingredients')->insert([
            // 1
            [
                'user_id' => 1,
                'recipe_id' => 1,
                'ingredient_name' => "スパゲティ", 
                'ingredient_category' => "穀類",
                'ingredient_quantity' => "200g",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 1,
                'ingredient_name' => "ベーコン", 
                'ingredient_category' => "肉類",
                'ingredient_quantity' => "4枚",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 1,
                'ingredient_name' => "モッツァレラチーズ", 
                'ingredient_category' => "乳製品",
                'ingredient_quantity' => "1袋(100g)",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 1,
                'ingredient_name' => "なす", 
                'ingredient_category' => "野菜類",
                'ingredient_quantity' => "2本",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 1,
                'ingredient_name' => "にんにく", 
                'ingredient_category' => "野菜類",
                'ingredient_quantity' => "1かけ",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 1,
                'ingredient_name' => "オリーブオイル", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "大さじ2",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 1,
                'ingredient_name' => "トマト缶", 
                'ingredient_category' => "野菜類",
                'ingredient_quantity' => "1/2缶(200g)",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 1,
                'ingredient_name' => "塩", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "小さじ1/2",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 1,
                'ingredient_name' => "こしょう", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "少々",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 1,
                'ingredient_name' => "コンソメ", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "小さじ1/2",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 1,
                'ingredient_name' => "バジル", 
                'ingredient_category' => "野菜類",
                'ingredient_quantity' => "4枚",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 2
            [
                'user_id' => 1,
                'recipe_id' => 2,
                'ingredient_name' => "白米", 
                'ingredient_category' => "穀類",
                'ingredient_quantity' => "どんぶり2杯(400g)",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 2,
                'ingredient_name' => "牛肉", 
                'ingredient_category' => "肉類",
                'ingredient_quantity' => "200g",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 2,
                'ingredient_name' => "塩", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "少々",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 2,
                'ingredient_name' => "こしょう", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "少々",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 2,
                'ingredient_name' => "にんにく", 
                'ingredient_category' => "野菜類",
                'ingredient_quantity' => "2かけ",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 2,
                'ingredient_name' => "オリーブオイル", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "大さじ1",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 2,
                'ingredient_name' => "白いりごま", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "大さじ2",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 2,
                'ingredient_name' => "細ねぎ", 
                'ingredient_category' => "野菜類",
                'ingredient_quantity' => "適量",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 2,
                'ingredient_name' => "しょうゆ", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "大さじ1/2",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 2,
                'ingredient_name' => "塩", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "小さじ1/3",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'recipe_id' => 2,
                'ingredient_name' => "バター", 
                'ingredient_category' => "乳製品",
                'ingredient_quantity' => "15g",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 3
            [
                'user_id' => 2,
                'recipe_id' => 3,
                'ingredient_name' => "スパゲティ", 
                'ingredient_category' => "穀類",
                'ingredient_quantity' => "160g",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 3,
                'ingredient_name' => "ベーコン", 
                'ingredient_category' => "肉類",
                'ingredient_quantity' => "4枚",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 3,
                'ingredient_name' => "レタス", 
                'ingredient_category' => "野菜類",
                'ingredient_quantity' => "4枚(120g)",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 3,
                'ingredient_name' => "にんにく", 
                'ingredient_category' => "野菜類",
                'ingredient_quantity' => "1かけ",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 3,
                'ingredient_name' => "唐辛子", 
                'ingredient_category' => "野菜類",
                'ingredient_quantity' => "少々",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 3,
                'ingredient_name' => "オリーブオイル", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "大さじ2",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 3,
                'ingredient_name' => "スパゲティのゆで汁", 
                'ingredient_category' => "その他",
                'ingredient_quantity' => "大さじ2",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 3,
                'ingredient_name' => "塩", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "小さじ1/2",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 3,
                'ingredient_name' => "こしょう", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "少々",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 4
            [
                'user_id' => 2,
                'recipe_id' => 4,
                'ingredient_name' => "白米", 
                'ingredient_category' => "穀類",
                'ingredient_quantity' => "どんぶり2杯(400g)",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 4,
                'ingredient_name' => "豚ひき肉", 
                'ingredient_category' => "肉類",
                'ingredient_quantity' => "150g",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 4,
                'ingredient_name' => "玉ねぎ", 
                'ingredient_category' => "野菜類",
                'ingredient_quantity' => "1/2個",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 4,
                'ingredient_name' => "しいたけ", 
                'ingredient_category' => "キノコ類",
                'ingredient_quantity' => "2個",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 4,
                'ingredient_name' => "半熟ゆで卵", 
                'ingredient_category' => "その他",
                'ingredient_quantity' => "1個",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 4,
                'ingredient_name' => "トマト缶", 
                'ingredient_category' => "野菜類",
                'ingredient_quantity' => "1/2缶(200g)",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 4,
                'ingredient_name' => "酒", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "大さじ2",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 4,
                'ingredient_name' => "しょうゆ", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "大さじ1",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 4,
                'ingredient_name' => "みそ", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "大さじ1/2",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 4,
                'ingredient_name' => "おろしにんにく", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "小さじ1/2",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 5
            [
                'user_id' => 2,
                'recipe_id' => 5,
                'ingredient_name' => "スパゲティ", 
                'ingredient_category' => "穀類",
                'ingredient_quantity' => "200g",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 5,
                'ingredient_name' => "菜の花", 
                'ingredient_category' => "野菜類",
                'ingredient_quantity' => "1束",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 5,
                'ingredient_name' => "トマト", 
                'ingredient_category' => "野菜類",
                'ingredient_quantity' => "1/2個",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 5,
                'ingredient_name' => "にんにく", 
                'ingredient_category' => "野菜類",
                'ingredient_quantity' => "1かけ",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 5,
                'ingredient_name' => "唐辛子", 
                'ingredient_category' => "野菜類",
                'ingredient_quantity' => "1本",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 5,
                'ingredient_name' => "昆布茶", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "少々",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 5,
                'ingredient_name' => "オリーブオイル", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "大さじ2",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 5,
                'ingredient_name' => "しょうゆ", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "大さじ1",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 5,
                'ingredient_name' => "塩", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "少々",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 5,
                'ingredient_name' => "こしょう", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "少々",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 6
            [
                'user_id' => 2,
                'recipe_id' => 6,
                'ingredient_name' => "スパゲティ", 
                'ingredient_category' => "穀類",
                'ingredient_quantity' => "80g",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 6,
                'ingredient_name' => "シーフードミックス", 
                'ingredient_category' => "魚類",
                'ingredient_quantity' => "100g",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 6,
                'ingredient_name' => "おろしにんにく", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "少々",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 6,
                'ingredient_name' => "オリーブオイル", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "小さじ1",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 6,
                'ingredient_name' => "バター", 
                'ingredient_category' => "乳製品",
                'ingredient_quantity' => "10g",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 6,
                'ingredient_name' => "大葉", 
                'ingredient_category' => "野菜類",
                'ingredient_quantity' => "2枚",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 6,
                'ingredient_name' => "酒", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "大さじ1",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 6,
                'ingredient_name' => "塩", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "小さじ1/3",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 6,
                'ingredient_name' => "めんつゆ", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "大さじ1/2",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 6,
                'ingredient_name' => "水", 
                'ingredient_category' => "その他",
                'ingredient_quantity' => "250cc",
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 7
            [
                'user_id' => 2,
                'recipe_id' => 7,
                'ingredient_name' => "じゃがいも", 
                'ingredient_category' => "芋類",
                'ingredient_quantity' => "2個",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 7,
                'ingredient_name' => "豚ロース肉", 
                'ingredient_category' => "肉類",
                'ingredient_quantity' => "2枚",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 7,
                'ingredient_name' => "スナップえんどう", 
                'ingredient_category' => "野菜類",
                'ingredient_quantity' => "6個",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 7,
                'ingredient_name' => "にんにく", 
                'ingredient_category' => "野菜類",
                'ingredient_quantity' => "1かけ",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 7,
                'ingredient_name' => "塩", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "少々",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 7,
                'ingredient_name' => "バター", 
                'ingredient_category' => "乳製品",
                'ingredient_quantity' => "少々",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 7,
                'ingredient_name' => "しょうゆ", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "少々",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 7,
                'ingredient_name' => "みりん", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "少々",
                'created_at' => now(),
                'updated_at' => now(),
            ],
             // 8
             [
                'user_id' => 2,
                'recipe_id' => 8,
                'ingredient_name' => "じゃがいも", 
                'ingredient_category' => "芋類",
                'ingredient_quantity' => "2個",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 8,
                'ingredient_name' => "玉ねぎ", 
                'ingredient_category' => "野菜類",
                'ingredient_quantity' => "1/4個",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 8,
                'ingredient_name' => "きゅうり", 
                'ingredient_category' => "野菜類",
                'ingredient_quantity' => "1/4本",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 8,
                'ingredient_name' => "にんじん", 
                'ingredient_category' => "野菜類",
                'ingredient_quantity' => "1/4本",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 8,
                'ingredient_name' => "ハム", 
                'ingredient_category' => "肉類",
                'ingredient_quantity' => "2枚",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 8,
                'ingredient_name' => "マヨネーズ", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "大さじ5",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 8,
                'ingredient_name' => "塩", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "少々",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'recipe_id' => 8,
                'ingredient_name' => "こしょう", 
                'ingredient_category' => "調味料",
                'ingredient_quantity' => "少々",
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}
